Build Rust image:
  image:
    name: docker:stable
  services:
    - name: docker:stable-dind
      alias: docker
  variables:
    IMAGE_ID: "${CI_REGISTRY_IMAGE}/rust:${CI_COMMIT_SHA}"
  script:
    - docker build -t "${IMAGE_ID}" .
  after_script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker push "${IMAGE_ID}"
